title:          yiny
exclude:        ['README.md', 'CNAME']
timezone:       Asia/shanghai
encoding:       'utf-8'
url:            http://yiny.net
ext_cn_site:    http://182.92.214.222
ext_us_site:    http://us.feling.net
permalink:      /:year/:month/:title.html
lsi:            true
markdown:       redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data", "html_toc"]
pygments: true
